import { MainWrapperProps } from "@/interfaces/props";
import Head from "next/head";
import Footer from "./Footer";
import Header from "./Header";

const MainWrapper = ({ children, title }: MainWrapperProps) => {
  return (
    <>
      <Head>
        <title>Kingdom Library</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Lora&display=swap"
          rel="stylesheet"
        />
      </Head>
      {children}
    </>
  );
};

export default MainWrapper;
