import { AdminWrapperProps } from "@/interfaces/props";
import Head from "next/head";
import Footer from "../Footer";
import Header from "./Header";

const AdminWrapper = ({ children, title }: AdminWrapperProps) => {
  return (
    <>
      <Head>
        <title>The Kingdom Library - Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Borel&family=Open+Sans&display=swap"
        />
      </Head>
      <Header />
      <main>
        <h1>{title}</h1>
        {children}
      </main>
      <Footer />
    </>
  );
};

export default AdminWrapper;
